name = "ABCDMatrixOptics"
uuid = "ccdfd77c-c9b6-493d-8c46-f34d2494ed29"
authors = ["Felix Wechsler (roflmaostc) <fxw+git@mailbox.org> and contributors"]
version = "0.4.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
ABCDMatrixOpticsPlotExt = "Plots"

[compat]
Colors = "0.12, 0.13"
Interpolations = "0.14, 0.15"
Parameters = "0.12"
PrecompileTools = "1"
RecipesBase = "1"
julia = "1, 1.9"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
